package br.jus.pjedash.entidade;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import br.jus.pjedash.comum.BaseEntity;

/**
 * Alerta generated by Edilson
 */
@Entity
@Table(name = Alerta.TABLE_NAME)
@SequenceGenerator(allocationSize = 1, name = "gen_alerta", sequenceName = "alerta_id_alerta_seq")
public class Alerta extends BaseEntity<Integer> {

	private static final long serialVersionUID = 4594625642635423343L;

	public static final String TABLE_NAME = "alerta";

	private Integer id;
	private String descricao;
	private Integer variavelId;
	private String variavelSigla;
	private String variavelDescricao;
	private Integer usuarioId;
	private Integer orgaoJulgadorId;
	private TipoAlerta tipoAlerta;
	private Double valorReferencia;
	
	@Id
	@GeneratedValue(generator = "gen_alerta", strategy = GenerationType.SEQUENCE)
	@Column(name = "id_alerta", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
		
	public Alerta() {
	}
	
	@Column(name = "descricao")
	@NotNull(message="Descrição do Alerta obrigatória")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Override
	public String toString() {
		return descricao;
	}

	@Column(name = "id_variavel")
	public Integer getVariavelId() {
		return variavelId;
	}

	public void setVariavelId(Integer variavelId) {
		this.variavelId = variavelId;
	}
	
	@Column(name = "id_usuario")
	public Integer getUsuarioId() {
		return usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}
	
	@OneToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="id_tipo_alerta")
	public TipoAlerta getTipoAlerta() {
		return tipoAlerta;
	}

	public void setTipoAlerta(TipoAlerta tipoAlerta) {
		this.tipoAlerta = tipoAlerta;
	}

	@Column(name = "valor_referencia")
	public Double getValorReferencia() {
		return valorReferencia;
	}

	public void setValorReferencia(Double valorReferencia) {
		this.valorReferencia = valorReferencia;
	}

	@Column(name = "variavel_sigla")
	public String getVariavelSigla() {
		return variavelSigla;
	}

	public void setVariavelSigla(String variavelSigla) {
		this.variavelSigla = variavelSigla;
	}

	@Column(name = "variavel_descricao")
	public String getVariavelDescricao() {
		return variavelDescricao;
	}

	public void setVariavelDescricao(String variavelDescricao) {
		this.variavelDescricao = variavelDescricao;
	}

	@Column(name = "id_orgaojulgador")
	public Integer getOrgaoJulgadorId() {
		return orgaoJulgadorId;
	}

	public void setOrgaoJulgadorId(Integer orgaoJulgadorId) {
		this.orgaoJulgadorId = orgaoJulgadorId;
	}
	
}