package br.jus.pjedash.entidade;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import br.jus.pjedash.comum.BaseEntity;

/**
 * Anotacao generated by Edilson
 */
@Entity
@Table(name = Anotacao.TABLE_NAME)
@SequenceGenerator(allocationSize = 1, name = "gen_anotacao", sequenceName = "anotacao_id_anotacao_seq")
public class Anotacao extends BaseEntity<Integer> {

	private static final long serialVersionUID = 4594625642635423343L;

	public static final String TABLE_NAME = "anotacao";

	private Integer id;
	private String texto;
	private String npuProcesso;
	private Integer orgaoJulgadorId;
	private Integer usuarioId;
	private Date data = new Date();
	private Date dataUltimaAlteracao = new Date();
	
	@Id
	@GeneratedValue(generator = "gen_anotacao", strategy = GenerationType.SEQUENCE)
	@Column(name = "id_anotacao", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
		
	public Anotacao() {
	}
	
	@Column(name = "anotacao_texto")
	@NotNull(message="Texto da Anotação obrigatório")
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Override
	public String toString() {
		return texto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "anotacao_data_hora", nullable = false)
	@NotNull(message="Data de criação obrigatória")
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "anotacao_ultima_alteracao")
	public Date getDataUltimaAlteracao() {
		return this.dataUltimaAlteracao;
	}

	public void setDataUltimaAlteracao(Date dataUltimaAlteracao) {
		this.dataUltimaAlteracao = dataUltimaAlteracao;
	}
	
	@Column(name = "npu_processo", length = 30)
	public String getNpuProcesso() {
		return npuProcesso;
	}

	public void setNpuProcesso(String npuProcesso) {
		this.npuProcesso = npuProcesso;
	}

	@Column(name = "id_usuario")
	public Integer getUsuarioId() {
		return usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}
	
	@Column(name = "id_orgaojulgador")
    public Integer getOrgaoJulgadorId() {
        return orgaoJulgadorId;
    }

    public void setOrgaoJulgadorId(Integer orgaoJulgadorId) {
        this.orgaoJulgadorId = orgaoJulgadorId;
    }

}
