package br.jus.pjedash.entidade;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.jus.pjedash.comum.BaseEntity;

/**
 * Tag generated by Edilson
 */
@Entity
@Table(name = ConfiguracaoOrgaoJulgador.TABLE_NAME)
@SequenceGenerator(allocationSize = 1, name = "gen_configuracao_orgjulg", sequenceName = "configuracao_orgjulg_id_configuracao_orgjulg_seq")
public class ConfiguracaoOrgaoJulgador extends BaseEntity<Integer> {

	private static final long serialVersionUID = 4594625642635423343L;

	public static final String TABLE_NAME = "configuracao_orgjulg";

	private Integer id;
	private String valor;
	private Configuracao configuracao;
	private Integer idOrgaoJulgador;
	private String usuarioUltimaAlteracao;
	private Date dataUltimaAlteracao = new Date();

	public ConfiguracaoOrgaoJulgador() {

	}

	@Id
	@GeneratedValue(generator = "gen_configuracao_orgjulg", strategy = GenerationType.SEQUENCE)
	@Column(name = "id_configuracao_orgjulg", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "valor")
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@ManyToOne(fetch = FetchType.EAGER, cascade=CascadeType.MERGE)
	@JoinColumn(name = "id_configuracao")
	public Configuracao getConfiguracao() {
		return configuracao;
	}

	public void setConfiguracao(Configuracao configuracao) {
		this.configuracao = configuracao;
	}

	@Column(name = "id_orgaojulgador")
	public Integer getIdOrgaoJulgador() {
		return idOrgaoJulgador;
	}

	public void setIdOrgaoJulgador(Integer idOrgaoJulgador) {
		this.idOrgaoJulgador = idOrgaoJulgador;
	}

	@Column(name = "usuario_ultima_alteracao")
	public String getUsuarioUltimaAlteracao() {
		return usuarioUltimaAlteracao;
	}

	public void setUsuarioUltimaAlteracao(String usuarioUltimaAlteracao) {
		this.usuarioUltimaAlteracao = usuarioUltimaAlteracao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ultima_alteracao")
	public Date getDataUltimaAlteracao() {
		return dataUltimaAlteracao;
	}

	public void setDataUltimaAlteracao(Date dataUltimaAlteracao) {
		this.dataUltimaAlteracao = dataUltimaAlteracao;
	}

}