package br.jus.pjedash.entidade;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import br.jus.pjedash.comum.BaseEntity;

/**
 * Tag generated by Edilson
 */
@Entity
@Table(name = Configuracao.TABLE_NAME)
@SequenceGenerator(allocationSize = 1, name = "gen_configuracao", sequenceName = "configuracao_id_configuracao_seq")
public class Configuracao extends BaseEntity<Integer> {

	private static final long serialVersionUID = 4594625642635423343L;

	public static final String TABLE_NAME = "configuracao";

	private Integer id;
	private String nome;
	private String descricao;
	private String valorDefault;
	private String tipoValor;
	private Integer tamanhoValor;
	private String listaOpcao;
	private String valorOpcao;
	private Secao secao;
	private List<ConfiguracaoOrgaoJulgador> configuracoesOrgao;

	public Configuracao() {

	}

	@Id
	@GeneratedValue(generator = "gen_configuracao", strategy = GenerationType.SEQUENCE)
	@Column(name = "id_configuracao", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", unique = true)
	@NotNull(message="Nome da Configuração obrigatória")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "valor_default")
	public String getValorDefault() {
		return this.valorDefault;
	}

	public void setValorDefault(String valorDefault) {
		this.valorDefault = valorDefault;
	}

	@Column(name = "tipo_valor")
	public String getTipoValor() {
		return this.tipoValor;
	}

	public void setTipoValor(String tipoValor) {
		this.tipoValor = tipoValor;
	}

	@Column(name = "tamanho_valor")
	public Integer getTamanhoValor() {
		return tamanhoValor;
	}

	public void setTamanhoValor(Integer tamanhoValor) {
		this.tamanhoValor = tamanhoValor;
	}

	@Column(name = "lista_opcao")
	public String getListaOpcao() {
		return listaOpcao;
	}

	public void setListaOpcao(String listaOpcao) {
		this.listaOpcao = listaOpcao;
	}

	@Column(name = "valor_opcao")
	public String getValorOpcao() {
		return valorOpcao;
	}

	public void setValorOpcao(String valorOpcao) {
		this.valorOpcao = valorOpcao;
	}

	@ManyToOne(fetch = FetchType.EAGER, cascade=CascadeType.MERGE)
	@JoinColumn(name = "id_secao")
	public Secao getSecao() {
		return secao;
	}

	public void setSecao(Secao secao) {
		this.secao = secao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configuracao")
	public List<ConfiguracaoOrgaoJulgador> getConfiguracoesOrgaoJulgador() {
		return configuracoesOrgao;
	}

	public void setConfiguracoesOrgaoJulgador(List<ConfiguracaoOrgaoJulgador> configuracoesOrgao) {
		this.configuracoesOrgao = configuracoesOrgao;
	}
}