package br.jus.pjedash.entidade;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import br.jus.pjedash.comum.BaseEntity;

/**
 * HistoricoAlerta generated by Edilson
 */
@Entity
@Table(name = HistoricoAlerta.TABLE_NAME)
@SequenceGenerator(allocationSize = 1, name = "gen_historico_alertas", sequenceName = "historico_alertas_id_historico_alertas_seq")
public class HistoricoAlerta extends BaseEntity<Integer> {

	private static final long serialVersionUID = 4594625642635423343L;

	public static final String TABLE_NAME = "historico_alertas";

	private Integer id;
	private Integer variavelId;
	private String variavelSigla;
	private String variavelDescricao;
	private Integer usuarioId;
	private Integer orgaoJulgadorId;
	private TipoAlerta tipoAlerta;
	private Double valorReferencia;
	private Double valorApurado;
	private Date dataOcorrencia = new Date();
	private boolean visualizado;
	
	@Id
	@GeneratedValue(generator = "gen_historico_alertas", strategy = GenerationType.SEQUENCE)
	@Column(name = "id_historico_alertas", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
		
	public HistoricoAlerta() {
	}
	
	@Override
	public String toString() {
		return id != null ? id.toString() : "";
	}

	@Column(name = "id_variavel")
	public Integer getVariavelId() {
		return variavelId;
	}

	public void setVariavelId(Integer variavelId) {
		this.variavelId = variavelId;
	}
	
	@Column(name = "id_usuario")
	public Integer getUsuarioId() {
		return usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}

	@OneToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="id_tipo_alerta")
	public TipoAlerta getTipoAlerta() {
		return tipoAlerta;
	}

	public void setTipoAlerta(TipoAlerta tipoAlerta) {
		this.tipoAlerta = tipoAlerta;
	}
	
	@Column(name = "valor_referencia")
	public Double getValorReferencia() {
		return valorReferencia;
	}

	public void setValorReferencia(Double valorReferencia) {
		this.valorReferencia = valorReferencia;
	}
	
	@Column(name = "valor_apurado")
	public Double getValorApurado() {
		return valorApurado;
	}

	public void setValorApurado(Double valorApurado) {
		this.valorApurado = valorApurado;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_ocorrencia", nullable = false)
	@NotNull(message="Data de ocorrência obrigatória")
	public Date getDataOcorrencia() {
		return this.dataOcorrencia;
	}

	public void setDataOcorrencia(Date dataOcorrencia) {
		this.dataOcorrencia = dataOcorrencia;
	}

	@Column(name = "visualizado")
	public boolean isVisualizado() {
		return visualizado;
	}

	public void setVisualizado(boolean visualizado) {
		this.visualizado = visualizado;
	}
	
	@Column(name = "variavel_sigla")
	public String getVariavelSigla() {
		return variavelSigla;
	}

	public void setVariavelSigla(String variavelSigla) {
		this.variavelSigla = variavelSigla;
	}

	@Column(name = "variavel_descricao")
	public String getVariavelDescricao() {
		return variavelDescricao;
	}

	public void setVariavelDescricao(String variavelDescricao) {
		this.variavelDescricao = variavelDescricao;
	}

	@Column(name = "id_orgaojulgador")
	public Integer getOrgaoJulgadorId() {
		return orgaoJulgadorId;
	}

	public void setOrgaoJulgadorId(Integer orgaoJulgadorId) {
		this.orgaoJulgadorId = orgaoJulgadorId;
	}
	
	
}