package br.jus.pjedash.entidade;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import br.jus.pjedash.comum.BaseEntity;

/**
 * ProcessoTag generated by Edilson
 */
@Entity
@Table(name = ProcessoTag.TABLE_NAME)
@SequenceGenerator(allocationSize = 1, name = "gen_processo_tag", sequenceName = "processo_tag_id_processo_tag_seq")
public class ProcessoTag extends BaseEntity<Integer> {

	private static final long serialVersionUID = 4594625642635423343L;

	public static final String TABLE_NAME = "processo_tag";

	private Integer id;
	private String npuProcesso;
	private Integer usuarioId;
	private Tag tag;
	
	public ProcessoTag() {
		
	}
	
	@Id
	@GeneratedValue(generator = "gen_processo_tag", strategy = GenerationType.SEQUENCE)
	@Column(name = "id_processo_tag", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
		
	@Column(name = "npu_processo", length = 30)
	public String getNpuProcesso() {
		return npuProcesso;
	}

	public void setNpuProcesso(String npuProcesso) {
		this.npuProcesso = npuProcesso;
	}
	
	@Column(name = "id_usuario")
	public Integer getUsuarioId() {
		return usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.PERSIST)
	@JoinColumn(name = "id_tag")
	public Tag getTag() {
		return tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}
	
}