package br.jus.pjedash.entidade;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import br.jus.pjedash.comum.BaseEntity;

/**
 * Secao generated by Edilson
 */
@Entity
@Table(name = Secao.TABLE_NAME)
@SequenceGenerator(allocationSize = 1, name = "gen_secao", sequenceName = "secao_id_secao_seq")
public class Secao extends BaseEntity<Integer> {

	private static final long serialVersionUID = 4594625642635423343L;

	public static final String TABLE_NAME = "secao";

	private Integer id;
	private String nome;
	private List<Configuracao> configuracoes;
	private Integer ordem;

	public Secao() {

	}

	@Id
	@GeneratedValue(generator = "gen_secao", strategy = GenerationType.SEQUENCE)
	@Column(name = "id_secao", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", unique = true)
	@NotNull(message="Nome da Seção obrigatória")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secao")
	public List<Configuracao> getConfiguracoes() {
		return configuracoes;
	}

	public void setConfiguracoes(List<Configuracao> configuracoes) {
		this.configuracoes = configuracoes;
	}

	@Column(name = "ordem")
	public Integer getOrdem() {
		return ordem;
	}

	public void setOrdem(Integer ordem) {
		this.ordem = ordem;
	}

}