package br.jus.pjedash.entidade;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import br.jus.pjedash.comum.BaseEntity;

/**
 * Tipo Alerta generated by Edilson
 */
@Entity
@Table(name = TipoAlerta.TABLE_NAME)
@SequenceGenerator(allocationSize = 1, name = "gen_tipo_alerta", sequenceName = "tipo_alerta_id_tipo_alerta_seq")
public class TipoAlerta extends BaseEntity<Integer> {

	private static final long serialVersionUID = 4594625642635423343L;

	public static final String TABLE_NAME = "tipo_alerta";

	private Integer id;
	private String descricao;
	private String tipo;
	
	@Id
	@GeneratedValue(generator = "gen_tipo_alerta", strategy = GenerationType.SEQUENCE)
	@Column(name = "id_tipo_alerta", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
		
	public TipoAlerta() {
	}
	
	@Column(name = "descricao", length = 100, unique = true)
	@Size.List({
		@Size(min=1, message="Descrição do Tipo Alerta não deve ser vazio"),
		@Size(max=100, message="Descrição do Tipo Alerta não deve ser maior que {max} caracteres")
		})
	@NotNull(message="Descrição do Tipo Alerta obrigatória")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "tipo")
	@NotNull(message="Tipo Alterta obrigatório")
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}
}